Component build sets up dockerx
This is because of this error I am getting on component builds:

```
ERROR: Cache export is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-cache-backends/
Error: buildx failed with: Learn more at https://docs.docker.com/go/build-cache-backends/
```

And the solution described here:

https://stackoverflow.com/questions/72707357/buildx-failed-with-error-cache-export-feature-is-currently-not-supported-for-d