Revert "Cache to and from are specified with mode max when building docker image"
This reverts commit 9db433e143a4bef55a20c443dd8876790010221d.

This was causing this error:

```
ERROR: Cache export is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-cache-backends/
Error: buildx failed with: Learn more at https://docs.docker.com/go/build-cache-backends/
```